### ISSUE TITLE
Unable to use Multi Projects with API Key token created on different Project.

### ISSUE THREAD

**Issue by tmallikarjuna** [gridscale/terraform-examples#7]
Even Though I am using a different project token to create resources on Gridscale, terraform is creating resources on default project only.

Please do fix this problem.

Terraform version: 0.13.4
GridScale Terraform Provider version: v1.7.4

**Comment by nvthongswansea** [comment]
Thanks for reporting the issue. We will take a look at it as soon as possible.

**Comment by nvthongswansea** [comment]
@tmallikarjuna According to [gridscale multi-project](https://github.com/gridscale/terraform-examples/tree/master/multi-project), you will need to source the `.envrc` file (or use a tool called "direnv" to easily switch between environment variables) before applying. The command to source the `.envrc` is `source .envrc`.

**Comment by nvthongswansea** [comment]
@tmallikarjuna btw, I will update the README file to highlight "source the .envrc file" part.

**Comment by nvthongswansea** [comment]
Another way to deal with the multiple project is to define a block as following in each `.tf` file:
```
provider "gridscale" {
  uuid = "uuid" ## This can be discarded; if you already set it in an environment variable, and the projects use the same user UUID
  token = "project-a-token"
}
```
For more info: https://registry.terraform.io/providers/gridscale/gridscale/latest/docs

**Comment by tmallikarjuna** [comment]
Hi Tom,

Thanks for the information. I was sourcing the .envrc file and the reason I don't know why it was overriding my default project's API key and maybe due to a global sourcing file was interrupting. Anyways, thanks for the info and the update of the guide.

Best regards,
Tejesh
